### ISSUE TITLE
`manager.py` cleanup

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/ecosystem#230]
### What is the expected enhancement?

In order to make developer experience better, let's cleanup `manager.py` and split all of it's function into clean modules, rather than have everything in one file.

Something like:
```
ecosystem/
    cli/
        test_group.py
        update_group.py
```

Groups can be implemented as functions https://github.com/google/python-fire/blob/master/docs/guide.md#version-2-firefiredict

**Comment by mickahell** [comment]
Split :
- test process
- website process
- members process
- ...

**Comment by mickahell** [comment]
They have some humor in the Fire community x) :
```
$ python example.py run
Ingesting! Nom nom nom...
Burp!
$ python example.py ingestion run
Ingesting! Nom nom nom...
$ python example.py digestion run
Burp!
$ python example.py digestion status
Satiated.
```
