### ISSUE TITLE
Parser failing on `!redo`

### ISSUE THREAD

**Issue by IceKhan13** [Qiskit/ecosystem#58]
### Steps to reproduce the problem
- create a submission issue or use https://github.com/qiskit-community/ecosystem/issues/21
- type `!redo` in comments
- go to https://github.com/qiskit-community/ecosystem/actions

### What is the current behavior?
Failing on `!redo`

<img width="1371" alt="Screen Shot 2021-10-21 at 4 34 00 PM" src="https://user-images.githubusercontent.com/8796709/138352694-08f675f0-102f-411c-bb70-826763628ffc.png">

### What is the expected behavior?
Should work on comment `!redo`.
Parser should work.

Need to write test cases with all variety of extra spaces, tabs, new line etc.

**Comment by IceKhan13** [comment]
@mickahell ping :)

**Comment by IceKhan13** [comment]
Logs https://github.com/qiskit-community/ecosystem/runs/3968809420?check_suite_focus=true

**Comment by mickahell** [comment]
I created a new one and it works for creation and redo : https://github.com/qiskit-community/ecosystem/issues/59
