### ISSUE TITLE
[Submission]: test the come back

### ISSUE THREAD

**Issue by mickahell** [Qiskit/ecosystem#59]
### Github repo

https://github.com/mickahell/quantum_pokemon-fight

### Description

...

### Email

toto@toto.fr

### License

MIT

### Tags

tool

**Comment by IceKhan13** [comment]
!redo

**Comment by IceKhan13** [comment]
!redo

**Comment by mickahell** [comment]
https://github.com/qiskit-community/ecosystem/runs/3969020856?check_suite_focus=true

**Comment by IceKhan13** [comment]
I just copy paste body from https://github.com/qiskit-community/ecosystem/issues/21

**Comment by mickahell** [comment]
the log chnage now it say here : `description = parse[3]`

**Comment by IceKhan13** [comment]
let's discuss it tomorrow, it can wait :)
