### ISSUE TITLE
[Submission]: qlasskit

### ISSUE THREAD

**Issue by dakk** [Qiskit/ecosystem#603]
### Github repo

https://github.com/dakk/qlasskit

### Description

Qlasskit is a Python library that allows quantum developers to write classical algorithms in pure Python and translate them into quantum circuits.

### Email

gessadavide@gmail.com

### License

Apache License 2.0

### Affiliations

The project is partially funded by the UnitaryFund microgrant.

### Labels

Converter

### Website

https://dakk.github.com/qlasskit

**Comment by frankharkins** [comment]
@dakk thanks! Can you sign the CLA (see https://github.com/Qiskit/ecosystem/pull/604#issuecomment-1829686700) so I can merge please?
