### ISSUE TITLE
[Submission]: qMuVi - An open-source quantum Music Video tool

### ISSUE THREAD

**Issue by garymooney** [Qiskit/ecosystem#634]
### Project name

qMuVi

### Github repo

https://github.com/garymooney/qmuvi

### Description

A library converting quantum circuits into audiovisual experiences, bridging the gap between complex quantum computations and human perception. It renders music videos that reveal the evolution of quantum states during algorithm processing, making quantum computing more intuitive and accessible.

### Email

gary.mooney4444@gmail.com

### License

GNU Library or "Lesser" General Public License (LGPL)

### Affiliations

The University of Melbourne

### Group

other

### Labels

Converter, Visualization

### Website

https://garymooney.github.io/qmuvi/

**Comment by garymooney** [comment]
Could we have a new label added "Education"?

**Comment by garymooney** [comment]
Is there a way to rerun the tests? I've just fixed an ecosystem.json format error. I'm using poetry and am still unsure if I've set it all up correctly.

**Comment by frankharkins** [comment]
@garymooney sorry about the tests. Please ignore them as we'll be removing them soon.

I'll add the label to your PR
