### ISSUE TITLE
Single source of truth for repository model

### ISSUE THREAD

**Issue by frankharkins** [Qiskit/ecosystem#655]
### What is the expected enhancement?

We keep breaking the website builds by adding invalid information to the TOML files. New submissions also need manually editing to make them valid. It would be good to ensure the issue template matches the TOML files and valid labels etc.

A possible solution is generating the issue template from a JSON schema.

**Comment by mickahell** [comment]
It seems you can do it using `jq` like `cat file.toml | grep jq .`

**Comment by frankharkins** [comment]
This was mostly addressed in #701; there are now only two "sources of truth" (the template and the repository model), but we have a test to make sure they stay in sync. I think this solution is good enough for now.
