### ISSUE TITLE
[Submission]: Exploring Dynamic Circuits through Gibbs Free Energy Calculations and Error Mitigation

### ISSUE THREAD

**Issue by AbdullahKazi500** [Qiskit/ecosystem#726]
### Project name

Exploring Dynamic Circuits through Gibbs Free Energy Calculations and Error Mitigation

### Github repo

https://github.com/owaisishtiaqsiddiqui/QRISE

### Description

The Project seeks to demonstrate the behavior of Gibbs free energy using dynamic mid-circuit measurements.
We Developed a framework for estimating the free energy of quantum systems using variational quantum algorithms. We Implemented ansatz parameterization techniques to construct parameterized quantum circuits capable of preparing quantum states relevant to the free energy calculation also Designed efficient algorithms for estimating expectation values of Hamiltonians and computing the free energy based on the obtained results and Evaluated the performance of the developed framework through empirical analysis, including benchmarking, optimization,

### Email

owaisishtiaq15@gmail.com

### Alternatives

There are no alternatives to this project but there are some tutorials on using Mid circuit measurements using Qiskit.

### License

MIT license

### Group

other

### Labels

Algorithms, Chemistry, Error mitigation, Jupyter notebook, Paper implementation, Physics

### Documentation

https://github.com/owaisishtiaqsiddiqui/QRISE/blob/main/QRise_Final_PPT.pdf

### Reference paper

https://arxiv.org/pdf/2005.08797.pdf, https://arxiv.org/pdf/2312.14139.pdf

**Comment by frankharkins** [comment]
Closing after discussion in with @AbdullahKazi500. We're reducing the scope of the ecosystem to projects that users can install and take advantage of, which excludes demos and research code. We still think this project is valuable and will try to find another home for it. In the meantime, the authors will write a blog post and present about this at a demo day on the 11th of July.
