### ISSUE TITLE
[Submission]: Grover controlled-diffuser (CUs)

### ISSUE THREAD

**Issue by albayaty** [Qiskit/ecosystem#764]
### Project name

Grover controlled-diffuser (CUs)

### Github repo

https://github.com/albayaty/grover_controlled_diffuser

### Description

The CUs is a new quantum diffusion operator for Grover’s algorithm to search for all correct solutions for Boolean oracles.

### Email

albayaty@pdx.edu

### Alternatives

There are no alternatives to this project.

### License

Apache License 2.0

### Affiliations

The Electrical and Computer Eng. Dept. at Portland State University.

### IBM maintenance status

- [ ] This project is officially maintained by IBM Quantum

### Group

applications

### Labels

Algorithms, Circuit building tool, Paper implementation

### Reference paper

https://doi.org/10.21203/rs.3.rs-2997276/v1

**Comment by frankharkins** [comment]
Closed as per https://github.com/Qiskit/ecosystem/pull/765#issuecomment-2294917537
